const meatballRecipes = [
"Classic Italian Meatballs with Marinara Sauce",  
"Swedish Meatballs with Cream Sauce",  
"Greek Keftedes Meatballs with Tzatziki",  
"Moroccan Spiced Meatballs",  
"Thai Curry Meatballs",  
"Mexican Albondigas Meatball Soup",  
"Vietnamese Meatball Pho",  
"Indian Kofta Meatball Curry",  
"Turkish Köfte Meatballs with Yogurt Sauce",  
"Chinese Lion's Head Meatballs",  
"Spanish Albondigas Meatballs in Tomato Sauce",  
"Lebanese Kafta Meatballs",  
"Korean Meatballs with Gochujang Sauce",  
"Russian Tefteli Meatballs in Sour Cream Sauce",  
"Polish Klopsiki Meatballs",  
"Dutch Bitterballen Meatballs",  
"Japanese Tsukune Meatballs",  
"Cuban Albondigas Meatball Soup",  
"Filipino Pork Meatballs",  
"Indonesian Bakso Meatballs",  
"Egyptian Kofta Meatballs",  
"American BBQ Meatballs",  
"British Faggots Meatballs",  
"Scottish Haggis Meatballs",  
"French Boulettes de Viande Meatballs",  
"German Frikadellen Meatballs",  
"Austrian Fleischlaibchen Meatballs",  
"Belgian Bitterballen Meatballs",  
"Danish Frikadeller Meatballs",  
"Norwegian Kjøttkaker Meatballs",  
"Finnish Lihapullat Meatballs",  
"Icelandic Kjötsúpa Meatballs",  
"Faroese Meatballs",  
"Estonian Lihapallid Meatballs",  
"Latvian Kotletes Meatballs",  
"Lithuanian Kotletai Meatballs",  
"Ukrainian Kotleti Meatballs",  
"Belarusian Kotleta Meatballs",  
"Russian Pozharskie Meatballs",  
"Armenian Kufta Meatballs",  
"Azerbaijani Kufta Meatballs",  
"Afghan Kofta Meatballs",  
"Pakistani Chapli Meatballs",  
"Bangladeshi Kofta Meatball Curry",  
"Sri Lankan Meatball Cutlets",  
"Bhutanese Ema Datshi with Meatballs",  
"Philippine Meatballs in Sweet and Sour Sauce",  
"Brunei Ambuyat with Meatballs",  
"Samoa Palusami with Meatballs",  
"Nauru Coconut Meatballs",  
"Micronesian Fish Meatballs",  
"Alaska Reindeer Meatballs",  
"Puerto Rican Albondigas Meatballs"
]; 