// Ricette e combinazioni per SchiacciArte
const schiacciateRecipes = [
"Schiacciata farcita con Prosciutto crudo con burrata e rucola",
"Schiacciata farcita con Gorgonzola con pere e noci",
"Schiacciata farcita con Salmone affumicato con crema di avocado",
"Schiacciata farcita con Melanzane grigliate con mozzarella di bufala",
"Schiacciata farcita con Nduja con ricotta e miele",
"Schiacciata farcita con Pomodori secchi con stracciatella e basilico",
"Schiacciata farcita con Cipolla caramellata con gorgonzola",
"Schiacciata farcita con Crema di funghi porcini con parmigiano",
"Schiacciata farcita con Pecorino stagionato con miele al tartufo",
"Schiacciata farcita con Verdure grigliate con hummus di ceci",
"Schiacciata farcita con Uova sode con maionese fatta in casa e capperi",
"Schiacciata farcita con Paté di olive con ricotta e scorza d'arancia",
"Schiacciata farcita con Mortadella con crema di pistacchio e granella",
"Schiacciata farcita con Bresaola con crema di formaggio e limone",
"Schiacciata farcita con Fichi freschi con caprino e pepe rosa",
"Schiacciata farcita con Zucchine marinate con feta e menta",
"Schiacciata farcita con Lardo di Colonnata con miele di castagno",
"Schiacciata farcita con Tonno sott'olio con cipolla rossa e pomodorini confit",
"Schiacciata farcita con Speck con crema di funghi e fontina",
"Schiacciata farcita con Radicchio con gorgonzola e noci tostate",
"Schiacciata farcita con Carciofi sott'olio con scaglie di parmigiano e limone",
"Schiacciata farcita con Salsiccia sbriciolata con crema di patate e rosmarino",
"Schiacciata farcita con Asiago con mostarda di frutta",
"Schiacciata farcita con Stracchino con acciughe del Cantabrico e scorza di lime",
"Schiacciata farcita con Pomodori secchi con crema di anacardi e basilico",
"Schiacciata farcita con Zucchine marinate con tofu affumicato e menta",
"Schiacciata farcita con Cipolla caramellata con crema di ceci e pepe nero",
"Schiacciata farcita con Crema di funghi porcini con prezzemolo fresco",
"Schiacciata farcita con Carciofi sott'olio con scorza di limone e pepe rosa",
"Schiacciata farcita con Paté di olive con pomodori secchi e rucola",
"Schiacciata farcita con Lenticchie speziate con cipolla rossa marinata",
"Schiacciata farcita con Chips di cavolo nero con crema di avocado",
"Schiacciata farcita con Barbabietola a fette con crema di noci",
"Schiacciata farcita con Peperoni arrosto con crema di mandorle e timo",
"Schiacciata farcita con Melanzane grigliate con tahina e sumac",
"Schiacciata farcita con Insalata di ceci, finocchio e scorza d’arancia",
"Schiacciata farcita con Cavolo viola marinato con senape dolce e semi tostati",
"Schiacciata farcita con Banana grigliata con crema di arachidi e peperoncino fresco",
"Schiacciata farcita con Patate lesse con senape rustica e cetriolini affettati",
"Schiacciata farcita con Mela verde con hummus e pepe affumicato",
"Schiacciata farcita con Marmellata di cipolle rosse con tofu affumicato",
"Schiacciata farcita con Crema di castagne con funghi saltati e olio al rosmarino",
"Schiacciata farcita con Tahina con cavolo viola marinato e coriandolo fresco",
"Schiacciata farcita con Crema di zucca con gocce di aceto balsamico e nocciole",
"Schiacciata farcita con Crema di piselli con menta e scorza di limone",
"Schiacciata farcita con Fragole marinate con rucola e pepe nero",
"Schiacciata farcita con Caffè amaro con mascarpone salato e speck croccante",
"Schiacciata farcita con Ostrica sgusciata con cetriolo marinato e crema di limone",
"Schiacciata farcita con Crema di patate con tartufo nero e scorza d’arancia",
"Schiacciata farcita con Crema di formaggio con polvere di caffè tostato e noci caramellate"
]; 